### PR TITLE
Update reference.md and README.md to Flex v2

### PR DESCRIPTION
**Pull request by westontrillium**

### CODE REVIEW

**Comment by LeoFrachet** [comment]
The only tiny tiny comment I would make is that MobilityData standardized the naming of GTFS extensions, and that therefore we slightly tend to advocate to write "GTFS-Flex" instead of "GTFS-flex".

But this is tiny tiny, and thanks for putting together the proposal and assembling it. Great job!

I've shared a few thoughts in the email I sent you just a bit earlier @thomastrillium, but overall LGTM

**Comment by thomastrillium** [comment]
Much appreciated and I have actually been thinking about this recently
whenever I type GTFS-flex and GTFS-Fares next to one another :)

Weston could you make this update?

**Comment by westontrillium** [comment]
@thomastrillium Capitalization change made to README.md.

**Comment by thomastrillium** [comment]
@scmcca I don't think I have the creds to merge this PR. Is that something you could go ahead and do?

**Pull request merged**
