### PR TITLE
Change prior_notice_last_time/prior_notice_start_time to (conditionally) optional fields

### PR DESCRIPTION
**Pull request by westontrillium**
prior_notice_last_time/prior_notice_start_time should not be conditionally required fields. There are cases in which a service has defined earliest/last days but unknown or undefined earliest/last times.

### CODE REVIEW

**Comment by tsherlockcraig** [comment]
And the assumption would be that if prior_notice_last_time is not filled, it's just assumed by consumer to be 24:00:00? I think we'd have to state that. And maybe we want to require the producer to just include 24:00:00 because that's not too tough and it removes the need for the exception?

**Comment by westontrillium** [comment]
Hmm, I agree it's not a heavy lift on the producer side, but:

1. Does a consumer need the start/last_time defined to understand that a prior_notice window without specific times refers to any trip query within a 24 hour day? I'm thinking that the logic "if search query is submitted after [date that matches `prior_notice_start_day`], X trip is valid" doesn't also need "...**at 00:00:00**..." since a date implies any time on that date... Does that make sense?

2. Are there risks in explicitly defining a start/last time when it's technically unknown? e.g., couldn't defining the start/last_time fields in this way potentially give a user false confidence that they still had time to book at an unlikely time like 23:55:00 when the specific timeframe that they can book within a day is _actually_ undefined?

Maybe my second point doesn't matter so much if these fields are more for defining behavior of what trips will show up based on when the user submits a query rather than when they can actually transact with the agency to book...?

**Comment by tsherlockcraig** [comment]
> 1. Does a consumer need the start/last_time defined to understand that a prior_notice window without specific times refers to any trip query within a 24 hour day?

I think yes, they do. The 24-hour day isn't really a stable thing in GTFS.

I think the current state of the spec in this regard should remain. The point of these fields is to make unambiguous when trips are allowed when prior_day_first/last_day are defined. The structure of requiring them when those fields are used is tailored and to the point.

**Comment by westontrillium** [comment]
Agree with keeping current requirement. See my comment [here](https://github.com/google/transit/pull/388#issuecomment-1644112827)

Closing this PR.

**Pull request closed without merging**
